const ADMIN = "ADMIN";
const ADMIN_USERS = "ADMIN_USERS";
const HOSPITAL_ADMIN = "HOSPITAL_ADMIN";
const HOSPITAL_DOCTOR = "HOSPITAL_DOCTOR";
const HOSPITAL_PATIENT = "HOSPITAL_PATIENT";
const HOSPITAL_TICKETS_ADMIN = "HOSPITAL_TICKETS_ADMIN";
const SALES_ADMIN = "SALES_ADMIN";
const SALES_CLIENT = "SALES_CLIENT";
const SALES_SELLER = "SALES_SELLER";
const SALES_ADMIN_RESTAURANT = "SALES_ADMIN_RESTAURANT";

const enumRoles = {
  ADMIN,
  ADMIN_USERS,
  HOSPITAL_ADMIN,
  HOSPITAL_DOCTOR,
  HOSPITAL_PATIENT,
  HOSPITAL_TICKETS_ADMIN,
  SALES_ADMIN,
  SALES_CLIENT,
  SALES_SELLER,
  SALES_ADMIN_RESTAURANT
};

export default enumRoles;
