const SYS_SALE_BILLING = "SYS_SALE_BILLING";
const SYS_AUTO_USER_REG = "SYS_AUTO_USER_REG";
const SYS_LOGIN_EMAIL_VERIFIED_REQUIRED = "SYS_LOGIN_EMAIL_VERIFIED_REQUIRED";

const systemPropertiesNames = {
  SYS_SALE_BILLING,
  SYS_AUTO_USER_REG,
  SYS_LOGIN_EMAIL_VERIFIED_REQUIRED
};

export default systemPropertiesNames;
