@ECHO OFF
ECHO RESTARTING DATABASES PUGGYSOFT.
SET DB_HOST=192.168.0.100
SET DB_PORT=3306
SET DB_USER=root
SET DB_PASSWORD=secret123
SET DB_NAME=puggysoftdb
REM CREATE DB.
REM mysqlsh --sql --host=192.168.0.100 -port:3306 --user=root --password=secret123 < db-init.sql
ECHO create data bases...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% < db-patches-create-db.sql
REM CREATE TABLES.
ECHO create users tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-01-users.sql
ECHO create hospital tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-02-hospital.sql
ECHO create sales tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-03-sales.sql
ECHO create reservation tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-04-reservation.sql
ECHO create facturacion tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-05-facturacion.sql
ECHO create projects tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-06-projects.sql
ECHO create qa tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-07-qa.sql
ECHO create pets tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-08-pets.sql
ECHO create contabilidad tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-09-contabilidad.sql
ECHO create asistencia tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-10-asistencia.sql
ECHO create planilla sueldos tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-11-planilla-sueldos.sql
ECHO create tickets tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-12-tickets.sql
ECHO create escuela tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-13-escuela-notas.sql
ECHO create alcaldia recursos municipales tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-14-alcaldia-recursos-municipales.sql
ECHO create alcaldia urbanismo tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-15-alcaldia-urbanismo-tramite.sql
ECHO create alcaldia regularizacion lotes tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-16-alcaldia-regularizacion-lotes.sql
ECHO create data storage tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-17-data-storage.sql
ECHO create mensualidad tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-18-mensualidad.sql
ECHO create condominio tables...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-tables-19-condominio.sql.sql

REM TRIGGERS AND STORE PROCEDURES.
ECHO create triggers and store procedures...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-create-triggers-and-store-procedures.sql

REM INSERT DATA.
ECHO insert users data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-01-users.sql
ECHO insert hospital data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-02-hospital.sql
ECHO insert sales data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-03-sales.sql
ECHO insert reservation data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-04-reservation.sql
ECHO insert facturacion data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-05-facturacion.sql
ECHO insert projects data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-06-projects.sql
ECHO insert qa data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-07-qa.sql
ECHO insert pets data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-08-pets.sql
ECHO insert contabilidad data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-09-contabilidad.sql
ECHO insert asistencia data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-10-asistencia.sql
ECHO insert planilla data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-11-planilla.sql
ECHO insert tickets data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-12-tickets.sql
ECHO insert escuela data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-13-escuela-notas.sql
ECHO insert alcaldia recursos municipales data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-14-alcaldia-recursos-municipales.sql
ECHO insert alcaldia urbanismo data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-15-alcaldia-urbanismo-tramite.sql
ECHO insert alcaldia regularizacion lotes data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-16-alcaldia-regularizacion-lotes.sql
ECHO insert data storage data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-17-data-storage.sql
ECHO insert data mensualidad data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-18-mensualidad.sql
ECHO insert data condominio data...
mysqlsh --sql --host=%DB_HOST% -port:%DB_PORT% --user=%DB_USER% --password=%DB_PASSWORD% --database=%DB_NAME% < db-patches-insert-data-test-19-condominio.sql
