-- ******* CONDOMINIO RECURSOS *******
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ALQUILER PARRILLERO A", 0, 50, 9999999, "ALQUILER PARRILLERO A POR UN DIA", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ALQUILER PARRILLERO B", 0, 50, 9999999, "ALQUILER PARRILLERO B POR UN DIA", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ALQUILER PARRILLERO C", 0, 50, 9999999, "ALQUILER PARRILLERO C POR UN DIA", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ALQUILER SALON", 0, 200, 9999999, "ALQUILER SALON POR UN DIA", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ENTRADA PSCINA/SAUNA PROPIETARIO", 0, 2, 9999999, "ENTRADA PSCINA/SAUNA PROPIETARIO", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("ENTRADA PSCINA/SAUNA INVITADO", 0, 10, 9999999, "ENTRADA PSCINA/SAUNA INVITADO", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("EXPENSAS DEPARTAMENTO UN CUARTO", 0, 150, 9999999, "EXPENSAS DEPARTAMENTO UN CUARTO", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("EXPENSAS DEPARTAMENTO DOS CUARTOS", 0, 250, 9999999, "EXPENSAS DEPARTAMENTO DOS CUARTOS", null, null, "N/A", null, null, "EMPRESA_3");
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock, code, tenant) VALUES ("EXPENSAS DEPARTAMENTO TRES CUARTOS", 0, 350, 9999999, "EXPENSAS DEPARTAMENTO TRES CUARTOS", null, null, "N/A", null, null, "EMPRESA_3");
