-- Insert data (Users).
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image) VALUES ("admin", "admin123", "0000000", "Admin", "Admin", "Admin", "Admin", "1990-01-01", "76479009", "Av. Villazon km-5", "Admin@gmail.com", null);
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("rseveric", "secret123", "5928025", "Richard", "Michael", "Severich",  "Zuares", "1994-05-26", "7008088", "Av. Blanco km-5", "Richard.Severich@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("cluza", "pass123",  "2365874", "Cory", "N/A", "Luza", "Ander", "1994-10-28", "700684700", "Av. Rojo km-10", "Cory.Luza@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mjacson", "secret255", "5123659", "Michael", "N/A", "Jackson", "Muller", "1984-02-15", "74600788", "Av. Azul km-11", "Michael.Jackson@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("cgarcia", "secret987", "8475651", "Charly", "N/A", "Garcia", "Perez", "2000-12-13", "74555505", "Av. Cafe km-5", "Charly.Garcia@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mrodrigo", "secret654", "1236548", "Rodrigo", "N/A", "Molina", "Sastre", "1988-11-11", "70065001", "Av. Muly km-5", "Rodrigo.Molina@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("client", "ins123", "0000001", "client", "N/A", "client", "client", "1990-01-01", "74644411", "Av. Castor", "client@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mmorriz", "mela123", "8745698", "Rick", "N/A", "Morris", "Duni", "1997-06-02", "74677884455", "Av. Pulpo", "Rick.Morris@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("rharris", "kass889", "5236567", "Rick", "N/A", "Harrys", "Calvo", "1989-08-15", "746778741", "Av. Mury", "Rick.Harrys@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("aflorez", "mula777", "7896321", "Andrea", "N/A", "Flores", "Rosas", "1997-07-06", "74633333", "Av. Curly", "Andrea.Flores@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("lzimpson", "cass222", "5928354", "Liza", "N/A", "Simpson", "Capry", "1992-03-18", "74874444", "Av. Sheeba", "Liza.Simpson@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("iortega", "upa4848", "2136545", "Iza", "N/A", "Ortega", "Mulry", "1995-05-27", "777889787", "Av. Good", "Iza.Ortega@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("esyler", "vela778", "7812653", "Emily", "N/A", "Syler", "Kratos", "1996-04-03", "74622214", "Av. Bad", "Emily.Syler@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mbros2",  "user555", "9814256","Mario", "N/A", "Bros", "Curva", "1999-08-08", "74677777", "Av. Los angeles", "Mario.Bros@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mbros1", "mela888", "6636666", "Mario", "N/A", "Mario","Bros", "1998-08-08", "74699999", "Av. Cultivo", "Mario.Bros@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mariel", "reyleon", "9825789", "Ariel", "N/A", "Moppu", "Arru", "1997-02-12", "74684517", "Av. Mi pesadilla", "Ariel.Moppu@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("mreyes", "pass555", "9985501", "Manfred", "N/A", "Reyes",  "Villa", "1985-12-25", "74451789", "Av. El escondite", "Manfred.Reyes@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("icruz", "mysecret", "9985502", "Igor", "N/A", "Cruz", "Loro", "1987-08-28", "74684784", "Av. Gusanito", "Igor.Cruz@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("dvera", "secret", "9985503",  "Daniel", "N/A", "Vera", "Serrano", "1997-03-11", "78884487", "Av. Webar", "Daniel.Vera@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("nasa", "nasa", "9985504", "Keyur", "N/A", "Rpuu", "Atroculope", "1997-04-10", "75594787", "Av. Inv. Las rutas", "Keyur.Rpuu@gmail.com", null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, telephone, address, email, image, created_by) VALUES ("micky", "secret123", "675849", "N/A", "miguel", "aguilar", "paredes", "1994-10-10", "77845322", "Av. B. Galindo", "10miguel94@gmail.com", null, "admin");

-- Insert data (Rols).
INSERT INTO rols (name, created_by) VALUES ("admin_super", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_user", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_sales_normal", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_sales_restaurant", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_hair_salon", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_inventory", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_human_resources", "admin");
INSERT INTO rols (name, created_by) VALUES ("admin_accountant", "admin");
INSERT INTO rols (name, created_by) VALUES ("client_hair_salon", "admin");

-- Insert data (User-Rols).
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1000, 1000, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1001, 1001, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1002, 1002, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1003, 1003, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1004, 1004, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1005, 1005, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1006, 1005, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1009, 1006, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1009, 1001, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1009, 1002, "admin");
INSERT INTO users_rols (id_user, id_rol, created_by) VALUES (1009, 1003, "admin");

-- Insert products
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cocacola 1L", 8, 10, 100, "Cocacola de un litro", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cocacola 2L", 10, 12, 100, "Cocacola de dos litros", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cocacola 3L", 12, 14, 100, "Cocacola de tres litros", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Nescafe Original Negro 200gr", 22, 27, 50, "Nescafe Original Negro de 200 gramos", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Leche pil 946ml", 10, 12, 100, "Leche pil en bolsa de 946 mili litros", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Wisky Johnny Walker", 220, 305, 35, "Cocacola de tres litros", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("CervezaTaqu", 19, 20, 80,"", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("CervezaHuar", 20, 25, 90,"", null, null, "Estante 3, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("CervezaCoro", 10, 15, 55,"", null, null, "Estante 3, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("CervezaCont", 4, 5, 100,"", null, null, "Estante 3, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Te Dharamsala", 15, 18, 39,"", null, null, "Estante 3, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Te Dharamsala", 15.50, 18.50, 39,"", null, null, "Estante 3, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza tibetana Barley", 17, 19, 17,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Sirope de regaliz",9,10, 13,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Especias Cajun del chef Anton",20, 22, 53,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Mezcla Gumbo del chef Anton", 15, 21, 35,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Mermelada de grosellas de la abuela", 20, 25, 120,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Peras secas orgánicas del tío Bob", 18, 30, 15,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salsa de arándanos Northwoods", 20, 40, 6,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Buey Mishi Kobe", 50, 97 ,29,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Pez espada", 15, 31, 31,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso Cabrales", 10, 21, 22,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso Manchego La Pastora", 25, 38, 86,"", null, null, "Estante 1, Nivel 3", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Algas Konbu", 4, 6, 24,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cuajada de judías", 20, 23.25, 35,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salsa de soja baja en sodio", 10, 15.50, 39,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Postre de merengue Pavlova", 10.50, 17.45, 29,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cordero Alice Springs",20.25, 39, 0,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Langostinos tigre Carnarvon", 30.45, 62.50, 42,"", null, null, "Estante 1, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Pastas de té de chocolate", 5.6, 9.20, 25,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Mermelada de Sir Rodney's",43.68, 81, 40,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Bollos de Sir Rodney's", 5, 10, 3,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Pan de centeno crujiente estilo Gustaf's", 15.5, 21, 104,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Pan fino", 5, 9, 61,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Refresco Guaraná Fantástica",6, 4.50, 20,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Crema de chocolate y nueces NuNuCa", 9, 14, 76,"", null, null, "Estante 4, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Ositos de goma Gumbär", 8, 31.23, 15,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Chocolate Schoggi",30, 43.90, 49,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Col fermentada Rössle", 35, 45.60, 26,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salchicha Thüringer", 68, 123.79, 0,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Arenque blanco del noroeste", 20, 25.89, 10,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso gorgonzola Telino", 10, 12.50, 0,"", null, null, "Estante 4, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso Mascarpone Fabioli", 30, 32, 9,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso de cabra", 1, 2.50, 112,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza Sasquatch", 3.5, 5.35, 111,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza negra Steeleye", 10, 18, 20,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Escabeche de arenque", 10, 19, 112,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salmón ahumado Gravad", 10, 26, 11,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Vino Côte de Blaye", 100, 263.50, 17,"", null, null, "Estante 8, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Licor verde Chartreuse", 15, 18, 69,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Carne de cangrejo de Boston", 9.4, 18.40, 123,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Crema de almejas estilo Nueva Inglaterra", 3.5, 9.65, 85,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Tallarines de Singapur", 13, 14, 26,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Café de Malasia", 30, 46, 17,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Azúcar negra Malacca", 13, 19.45, 27,"", null, null, "Estante 10, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Arenque ahumado", 7, 9.50, 5,"", null, null, "Estante 9, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Arenque salado", 7, 12, 95,"", null, null, "Estante 9, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Galletas Zaanse", 8, 9.50, 36,"", null, null, "Estante 9, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Chocolate holandés", 10.5, 12.75, 15,"", null, null, "Estante 9, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Regaliz", 13.45, 20, 10,"", null, null, "Estante 9, Nivel 5", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Chocolate blanco", 8.90, 16.25, 65,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Manzanas secas Manjimup", 38.35, 53, 20,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cereales para Filo",3, 7 ,38,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Empanada de carne", 32.80, 38.85, 0,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Empanada de cerdo", 6.20, 7.45, 21,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Paté chino", 20, 24, 115,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Gnocchi de la abuela Alicia", 30, 38, 21,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Raviolis Angelo", 15.10, 19.50, 36,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Caracoles de Borgoña", 12.45, 18.25, 62,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Raclet de queso Courdavault", 37, 55, 79,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Camembert Pierrot", 25, 34, 19,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Sirope de arce", 11, 28.50, 113,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Tarta de azúcar", 27, 49.30, 17,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Sandwich de vegetales", 32, 43.90, 24,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Bollos de pan de Wimmer", 28, 33.25, 22,"", null, null, "Estante 7, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salsa de pimiento picante de Luisiana", 17, 21.05, 76,"", null, null, "Estante 5, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Especias picantes de Luisiana", 14, 17, 4,"", null, null, "Estante 5, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza Laughing Lumberjack", 6, 14, 52,"", null, null, "Estante 5, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Barras de pan de Escocia", 6, 12.50, 6,"", null, null, "Estante 5, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso Gudbrandsdals", 8, 36 ,26,"", null, null, "Estante 5, Nivel 2", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza Outback", 10, 15, 15,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Crema de queso Fløtemys", 10, 21.50, 26,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso Mozzarella Giovanni", 15, 34.80, 14,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Caviar rojo", 7, 15, 101,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Queso de soja Longlife", 5, 10, 4,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Cerveza Klosterbier Rhönbräu", 3, 7.75 ,125,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Licor Cloudberry", 9, 18 ,57,"", null, null, "Estante 5, Nivel 1", null);
INSERT INTO products (name, purchase_price, sale_price, stock, description, image, bar_code, location, minimum_stock) VALUES ("Salsa verde original Frankfurter", 5, 13 ,32,"", null, null, "Estante 5, Nivel 1", null);
