-- Insert data (Users).
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image) VALUES ("admin", "admin123", "0000000", "Admin", "Admin", "Admin", "Admin", "1990-01-01", 25, 'MALE', 'Ing. Informatico', "76479009", "Av. Villazon km-5", "Admin@gmail.com", true, null);
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("adminhospital", "admin123", "111111787", "N/A", "adminhospital", "adminhospital", "adminhospital", "1990-10-10", 50, 'MALE', 'Admin Hospital', "76479666", "Av. B. Galindo", "adminhospital@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("doctor", "admin123", "466587777", "N/A", "doctor", "doctor", "doctor", "1990-10-10", 50, 'MALE', 'Medico General', "76487888", "Av. B. Galindo", "doctor@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("paciente", "admin123", "4548787", "N/A", "paciente", "paciente", "paciente", "1990-10-10", 50, 'MALE', 'Chef', "76487888", "Av. B. Galindo", "paciente@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("adminfichas", "admin123", "454878888", "N/A", "adminfichas", "adminfichas", "adminfichas", "1990-10-10", 50, 'MALE', 'Ing. Comercial', "76487888", "Av. B. Galindo", "paciente@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("rseveric", "secret123", "5928025", "Richard", "Michael", "Severich",  "Zuares", "1994-05-26", 25, 'MALE', 'Ing. Sistemas', "7008088", "Av. Blanco km-5", "Richard.Severich@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("cluza", "pass123",  "2365874", "Cory", "N/A", "Luza", "Ander", "1994-10-28", 28, 'MALE', 'Ing. Sistemas', "700684700", "Av. Rojo km-10", "Cory.Luza@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mjacson", "secret255", "5123659", "Michael", "N/A", "Jackson", "Muller", "1984-02-15", 25, 'MALE', 'Ing. Sistemas', "74600788", "Av. Azul km-11", "Michael.Jackson@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("cgarcia", "secret987", "8475651", "Charly", "N/A", "Garcia", "Perez", "2000-12-13", 25, 'MALE', 'Ing. Sistemas', "74555505", "Av. Cafe km-5", "Charly.Garcia@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mrodrigo", "secret654", "1236548", "Rodrigo", "N/A", "Molina", "Sastre", "1988-11-11", 80, 'MALE', 'Ing. Sistemas', "70065001", "Av. Muly km-5", "Rodrigo.Molina@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("client", "ins123", "0000001", "client", "N/A", "client", "client", "1990-01-01", 25, 'MALE', 'Ing. Logistica', "74644411", "Av. Castor", "client@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mmorriz", "mela123", "8745698", "Rick", "N/A", "Morris", "Duni", "1997-06-02", 60, 'MALE', 'Medico General', "74677884455", "Av. Pulpo", "Rick.Morris@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("rharris", "kass889", "5236567", "Rick", "N/A", "Harrys", "Calvo", "1989-08-15", 25, 'MALE', 'Ing. Sistemas', "746778741", "Av. Mury", "Rick.Harrys@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("aflorez", "mula777", "7896321", "Andrea", "N/A", "Flores", "Rosas", "1997-07-06", 25, 'FEMALE', 'Ing. Electronica', "74633333", "Av. Curly", "Andrea.Flores@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("lzimpson", "cass222", "5928354", "Liza", "N/A", "Simpson", "Capry", "1992-03-18", 25, 'FEMALE', 'Lic. Matamaticas', "74874444", "Av. Sheeba", "Liza.Simpson@gmail.com", true, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("iortega", "upa4848", "2136545", "Iza", "N/A", "Ortega", "Mulry", "1995-05-27", 25, 'FEMALE', 'Contador', "777889787", "Av. Good", "Iza.Ortega@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("esyler", "vela778", "7812653", "Emily", "N/A", "Syler", "Kratos", "1996-04-03", 25, 'FEMALE', 'Ing. Comercial', "74622214", "Av. Bad", "Emily.Syler@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mbros2",  "user555", "9814256","Mario", "N/A", "Bros", "Curva", "1999-08-08", 20, 'MALE', 'Ing. Civil', "74677777", "Av. Los angeles", "Mario.Bros@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mbros1", "mela888", "6636666", "Mario", "N/A", "Mario","Bros", "1998-08-08", 25, 'MALE', 'Ing. Mecanica', "74699999", "Av. Cultivo", "Mario.Bros@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mariel", "reyleon", "9825789", "Ariel", "N/A", "Moppu", "Arru", "1997-02-12", 40, 'MALE', 'Contaduria publica', "74684517", "Av. Mi pesadilla", "Ariel.Moppu@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("mreyes", "pass555", "9985501", "Manfred", "N/A", "Reyes",  "Villa", "1985-12-25", 25, 'MALE', 'Ing. Sistemas', "74451789", "Av. El escondite", "Manfred.Reyes@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("icruz", "mysecret", "9985502", "Igor", "N/A", "Cruz", "Loro", "1987-08-28", 45, 'MALE', 'Ing. Sistemas', "74684784", "Av. Gusanito", "Igor.Cruz@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("dvera", "secret", "9985503",  "Daniel", "N/A", "Vera", "Serrano", "1997-03-11", 25, 'MALE', 'Adm. Empresas', "78884487", "Av. Webar", "Daniel.Vera@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("nasa", "nasa", "9985504", "Keyur", "N/A", "Rpuu", "Atroculope", "1997-04-10", 25, 'MALE', 'Lic. Fisica', "75594787", "Av. Inv. Las rutas", "Keyur.Rpuu@gmail.com", false, null, "admin");
INSERT INTO users (username, password, dni, name, second_name, last_name, second_last_name, birth_date, age, sex, occupation, telephone, address, email, active, image, created_by) VALUES ("micky", "secret123", "675849", "N/A", "miguel", "aguilar", "paredes", "1994-10-10", 25, 'MALE', 'Lic. Administracion', "77845322", "Av. B. Galindo", "10miguel94@gmail.com", false, null, "admin");

-- Insert data (Roles).
INSERT INTO roles (name, created_by) VALUES ("ADMIN", "admin");
INSERT INTO roles (name, created_by) VALUES ("ADMIN_USERS", "admin");
INSERT INTO roles (name, created_by) VALUES ("HOSPITAL_ADMIN", "admin");
INSERT INTO roles (name, created_by) VALUES ("HOSPITAL_DOCTOR", "admin");
INSERT INTO roles (name, created_by) VALUES ("HOSPITAL_PATIENT", "admin");
INSERT INTO roles (name, created_by) VALUES ("HOSPITAL_TICKETS_ADMIN", "admin");
INSERT INTO roles (name, created_by) VALUES ("SALES_ADMIN", "admin");
INSERT INTO roles (name, created_by) VALUES ("SALES_CLIENT", "admin");
INSERT INTO roles (name, created_by) VALUES ("SALES_SELLER", "admin");

-- Insert data (User-Roles).
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1000, 1000, "admin"); -- Admin Full.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1000, 1002, "admin"); -- Admin Full.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1001, 1002, "admin"); -- Admin hospital.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1002, 1003, "admin"); -- Admin doctor.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1003, 1004, "admin"); -- Admin patient.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1004, 1005, "admin"); -- Admin tickets admin.
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1008, 1001, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1009, 1003, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1010, 1003, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1011, 1003, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1012, 1003, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1009, 1004, "admin");
INSERT INTO users_roles (id_user, id_role, created_by) VALUES (1009, 1008, "admin");
